---
abstract: 'Easy OO access to complex perl data structures'
author:
  - 'Peter Shangov <pshangov@yahoo.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-AsObject
requires:
  Carp: 0
  Scalar::Util: 0
  Sub::Exporter: 0
  namespace::clean: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-AsObject
  homepage: http://github.com/pshangov/data-asobject/tree
  repository: git://github.com/pshangov/data-asobject.git
version: 0.07
